#!/usr/bin/env bash
#Configure the nginx server to another page and 
sudo apt update -y
sudo apt install nginx -y

config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm indxex.nginx-debian.html;
        server_name _;
    add_header X-Server-By \$HOSTNAME;
    }
"
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "$config" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart

