#!/usr/bin/env bash
#Installs and configures web server
#Update and install nginx
apt-get update -y
apt-get install nginx -y


#Set the default page to contain "Holberton School"
echo "Holberton School" > /var/www/html/index..html

#Restart nginx withot systemct1
service nginx restart
