#!/usr/bin/env bash
# Configures a new Ubuntu machine with nginx, Holberton School page, and 301 redirect on /redirect_me

sudo apt-get update -y
sudo apt-get install -y nginx
ufw alow 'Nginx HTTP'

echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Configure nginx with 301 redirect on /redirect_me
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites/available/default

sudo service nginx restart
