#!/usr/bin/env bash
# Configures a new Ubuntu machine with nginx, Holberton School page, and 301 redirect on /redirect_me

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure nginx with 301 redirect on /redirect
sudo sed -i 's|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}|' /etc/nginx/sites-available/default

sudo service nginx restart
